// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciaymvntmwwbnvewedue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpYXltdm50bXd3Ym52ZXdlZHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODYwNTYsImV4cCI6MjA1OTg2MjA1Nn0.j-Pxl8giaNpJz4-hUXVylcZE16jg1UIPkC5miN8UJ7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);